# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/ (optional)
url: "http://www.your-domain.com" # the base hostname & protocol for your site

# to run server on C9 run below line:
# jekyll serve --host $IP --port $PORT --baseurl ''


# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: Brian Mont # Your name will go here
  description: "A personal portfolio and blog website" # used by search engines

  # Header and footer text
  header_text: >
     <h1>Student & Web Developer</h1>
     <p>I'm a kickass developer specializing in Rails, AngularJS, and React/Redux.</p>
  header_text_feature_image:
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> and made with love.

  # Icons
  rss: false
  email_address: "briansmont830@gmail.com"
  behance:
  bitbucket:
  dribbble:
  facebook: "brian.mont.50"
  flickr:
  github: "/briansmont"
  google_plus:
  instagram: "briansmont"
  linkedin:  "https://www.linkedin.com/in/brian-mont-a3037943/"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-90766981-1"
  disqus_shortname:
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Read more &raquo;"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Lato:300,400,700,300italic,700italic|Abril+Fatface"

# PAGINATION
paginate: 100
paginate_path: "blog/page:num"

# COLLECTIONS
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# BUILD SETTINGS
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed

gems: [jekyll-paginate, octopress-debugger]
